// Copyright (c) 2024 Computer Vision Center (CVC) at the Universitat Autonoma
// de Barcelona (UAB).
//
// This work is licensed under the terms of the MIT license.
// For a copy, see <https://opensource.org/licenses/MIT>.

#pragma once

#include "carla/rpc/Location.h"
#include "carla/sensor/data/SemanticLidarData.h"

#include <cstdint>
#include <vector>

namespace carla {

namespace ros2 {
  class ROS2;
}

namespace sensor {

namespace s11n {
  class LidarSerializer;
  class LidarHeaderView;
}

namespace data {

  /// Helper class to store and serialize the data generated by a Lidar.
  ///
  /// The header of a Lidar measurement consists of an array of uint32_t's in
  /// the following layout
  ///
  ///    {
  ///      Horizontal angle (float),
  ///      Channel count,
  ///      Point count of channel 0,
  ///      ...
  ///      Point count of channel n,
  ///    }
  ///
  /// The points are stored in an array of floats
  ///
  ///    {
  ///      X0, Y0, Z0, I0
  ///      ...
  ///      Xn, Yn, Zn, In
  ///    }
  ///

  class LidarDetection {
    public:
      geom::Location point;
      float intensity;
      uint16_t ring;  // 激光线号（通道ID），默认为0
      float time;     // 点的时间戳（相对于扫描开始的时间，秒），默认为0.0f

      LidarDetection() :
          point(0.0f, 0.0f, 0.0f), intensity{0.0f}, ring{0}, time{0.0f} { }
      LidarDetection(float x, float y, float z, float intensity) :
          point(x, y, z), intensity{intensity}, ring{0}, time{0.0f} { }
      LidarDetection(geom::Location p, float intensity) :
          point(p), intensity{intensity}, ring{0}, time{0.0f} { }
      LidarDetection(float x, float y, float z, float intensity, uint16_t ring_id, float point_time) :
          point(x, y, z), intensity{intensity}, ring{ring_id}, time{point_time} { }
      LidarDetection(geom::Location p, float intensity, uint16_t ring_id, float point_time) :
          point(p), intensity{intensity}, ring{ring_id}, time{point_time} { }

      void WritePlyHeaderInfo(std::ostream& out) const{
        out << "property float32 x\n" \
          "property float32 y\n" \
          "property float32 z\n" \
          "property float32 I";
      }

      void WriteDetection(std::ostream& out) const{
        out << point.x << ' ' << point.y << ' ' << point.z << ' ' << intensity;
      }
  };

  class LidarData : public SemanticLidarData{

  public:
    explicit LidarData(uint32_t ChannelCount = 0u)
      : SemanticLidarData(ChannelCount) {
    }

    LidarData &operator=(LidarData &&) = default;

    ~LidarData() = default;

    virtual void ResetMemory(std::vector<uint32_t> points_per_channel) {
      DEBUG_ASSERT(GetChannelCount() > points_per_channel.size());
      std::memset(_header.data() + Index::SIZE, 0, sizeof(uint32_t) * GetChannelCount());

      uint32_t total_points = static_cast<uint32_t>(
          std::accumulate(points_per_channel.begin(), points_per_channel.end(), 0));

      _points.clear();
      _points.reserve(total_points * 4);
      
      // 可选：为ring和time分配内存（如果使用扩展格式）
      _rings.clear();
      _times.clear();
      _rings.reserve(total_points);
      _times.reserve(total_points);
    }

    void WritePointSync(LidarDetection &detection) {
      _points.emplace_back(detection.point.x);
      _points.emplace_back(detection.point.y);
      _points.emplace_back(detection.point.z);
      _points.emplace_back(detection.intensity);
      
      // 如果detection包含ring和time信息，存储它们
      _rings.emplace_back(detection.ring);
      _times.emplace_back(detection.time);
    }
    
    // 检查是否包含ring和time信息
    bool HasRingAndTime() const {
      const size_t point_count = _points.size() / 4;
      return (_rings.size() == point_count && _times.size() == point_count);
    }

    virtual void WritePointSync(SemanticLidarDetection &detection) {
      (void) detection;
      DEBUG_ASSERT(false);
    }

  private:
    std::vector<float> _points;
    std::vector<uint16_t> _rings;  // 可选的ring信息，与_points中的点一一对应
    std::vector<float> _times;    // 可选的时间信息，与_points中的点一一对应

    friend class s11n::LidarSerializer;
    friend class s11n::LidarHeaderView;
    friend class carla::ros2::ROS2;
  };

} // namespace s11n
} // namespace sensor
} // namespace carla
