// Copyright (c) 2024 Computer Vision Center (CVC) at the Universitat Autonoma
// de Barcelona (UAB).
//
// This work is licensed under the terms of the MIT license.
// For a copy, see <https://opensource.org/licenses/MIT>.

#pragma once

#include "carla/rpc/Location.h"
#include "carla/sensor/data/SemanticLidarData.h"

#include <cstdint>
#include <vector>

namespace carla {

namespace ros2 {
  class ROS2;
}

namespace sensor {

namespace s11n {
  class LidarSerializer;
  class LidarHeaderView;
}

namespace data {

  /// Helper class to store and serialize the data generated by a Lidar.
  ///
  /// The header of a Lidar measurement consists of an array of uint32_t's in
  /// the following layout
  ///
  ///    {
  ///      Horizontal angle (float),
  ///      Channel count,
  ///      Point count of channel 0,
  ///      ...
  ///      Point count of channel n,
  ///    }
  ///
  /// The points are stored as an array of LidarDetection structures (24 bytes each)
  ///
  ///    {
  ///      X0, Y0, Z0, I0, ring0, padding0, time0
  ///      ...
  ///      Xn, Yn, Zn, In, ringn, paddingn, timen
  ///    }
  ///
  /// Each LidarDetection is 24 bytes: x(4) + y(4) + z(4) + intensity(4) + ring(2) + padding(2) + time(4)
  ///

  // 注意：LidarDetection 的大小必须保持为 24 字节，
  // 以兼容 LidarMeasurement/LidarSerializer 中的内存布局。
  // 结构：x(4) + y(4) + z(4) + intensity(4) + ring(2) + padding(2) + time(4) = 24字节
  // 注意：不使用 geom::Location，而是直接使用三个 float，避免继承带来的对齐问题
  #pragma pack(push, 1)
  class LidarDetection {
    public:
      float x;
      float y;
      float z;
      float intensity;
      uint16_t ring;
      uint16_t padding;  // 用于对齐，确保 time 的偏移量为 20
      float time;
      
      // 提供 point 访问器以保持兼容性
      geom::Location GetPoint() const {
        return geom::Location(x, y, z);
      }
      
      void SetPoint(const geom::Location& p) {
        x = p.x;
        y = p.y;
        z = p.z;
      }

      LidarDetection() :
          x(0.0f), y(0.0f), z(0.0f), intensity{0.0f}, ring{0u}, padding{0u}, time{0.0f} { }
      LidarDetection(float ix, float iy, float iz, float intensity) :
          x(ix), y(iy), z(iz), intensity{intensity}, ring{0u}, padding{0u}, time{0.0f} { }
      LidarDetection(geom::Location p, float intensity) :
          x(p.x), y(p.y), z(p.z), intensity{intensity}, ring{0u}, padding{0u}, time{0.0f} { }
      LidarDetection(float ix, float iy, float iz, float intensity, uint16_t ring, float time) :
          x(ix), y(iy), z(iz), intensity{intensity}, ring{ring}, padding{0u}, time{time} { }
      LidarDetection(geom::Location p, float intensity, uint16_t ring, float time) :
          x(p.x), y(p.y), z(p.z), intensity{intensity}, ring{ring}, padding{0u}, time{time} { }

      void WritePlyHeaderInfo(std::ostream& out) const{
        out << "property float32 x\n" \
          "property float32 y\n" \
          "property float32 z\n" \
          "property float32 I\n" \
          "property uint16 ring\n" \
          "property float32 time";
      }

      void WriteDetection(std::ostream& out) const{
        out << x << ' ' << y << ' ' << z << ' ' << intensity 
            << ' ' << ring << ' ' << time;
      }
  };
  #pragma pack(pop)

  // 这个结构是给UE向LibCarla传信息用的，在ROS2.CPP会解析
  class LidarData : public SemanticLidarData{

  public:
    explicit LidarData(uint32_t ChannelCount = 0u)
      : SemanticLidarData(ChannelCount) {
    }

    LidarData &operator=(LidarData &&) = default;

    ~LidarData() = default;

    virtual void ResetMemory(std::vector<uint32_t> points_per_channel) {
      DEBUG_ASSERT(GetChannelCount() > points_per_channel.size());
      std::memset(_header.data() + Index::SIZE, 0, sizeof(uint32_t) * GetChannelCount());

      uint32_t total_points = static_cast<uint32_t>(
          std::accumulate(points_per_channel.begin(), points_per_channel.end(), 0));

      _points.clear();
      // 每个点 24 字节：x(4) + y(4) + z(4) + intensity(4) + ring(2) + padding(2) + time(4)
      _points.reserve(total_points * sizeof(LidarDetection));
    }

    // 写入点数据（包含 ring 和 time）
    void WritePointSync(LidarDetection &detection) {
      // 直接将 LidarDetection 结构体作为字节追加
      const uint8_t* detection_bytes = reinterpret_cast<const uint8_t*>(&detection);
      _points.insert(_points.end(), detection_bytes, detection_bytes + sizeof(LidarDetection));
    }

    virtual void WritePointSync(SemanticLidarDetection &detection) {
      (void) detection;
      DEBUG_ASSERT(false);
    }

  private:
    // 存储为字节数组，每个点 24 字节：x(4) + y(4) + z(4) + intensity(4) + ring(2) + padding(2) + time(4)
    std::vector<uint8_t> _points;

    friend class s11n::LidarSerializer;
    friend class s11n::LidarHeaderView;
    friend class carla::ros2::ROS2;
  };

} // namespace s11n
} // namespace sensor
} // namespace carla
